--==================================
--DATA VALIDATION
--==================================
--LISTING ALL TABLES
SELECT table_name
FROM user_tables
ORDER BY table_name;
  
--ROW COUNT OF ALL TABLE   
SELECT COUNT(*) FROM ACCOUNTS;
SELECT COUNT(*) FROM CLIENTS;
SELECT COUNT(*) FROM CARDS;
SELECT COUNT(*) FROM DISPOSITION;
SELECT COUNT(*) FROM DISTRICT;
SELECT COUNT(*) FROM LOAN;
SELECT COUNT(*) FROM ORDER_;
SELECT COUNT(*) FROM TRANSACTIONS;

--PREVIEW DATA
SELECT *
FROM ACCOUNTS
WHERE ROWNUM <= 10;

SELECT *
FROM CLIENTS
WHERE ROWNUM <= 10;

SELECT *
FROM CARDS
WHERE ROWNUM <= 10;

SELECT *
FROM DISPOSITION
WHERE ROWNUM <= 10;

SELECT *
FROM DISTRICT
WHERE ROWNUM <= 10;

SELECT *
FROM LOAN
WHERE ROWNUM <= 10;

SELECT *
FROM ORDER_
WHERE ROWNUM <= 10;

SELECT *
FROM TRANSACTIONS
WHERE ROWNUM <= 10;
