--==================================
--DATA CLEANING
--==================================

-- DUPLICATE CHECK
SELECT ACCOUNT_ID,COUNT(*)
FROM ACCOUNTS
GROUP BY ACCOUNT_ID
HAVING COUNT(*)>1;

SELECT CLIENT_ID,COUNT(*)
FROM CLIENTS
GROUP BY CLIENT_ID
HAVING COUNT(*)>1;

SELECT LOAN_ID,COUNT(*)
FROM LOAN
GROUP BY LOAN_ID
HAVING COUNT(*)>1;

SELECT TRANS_ID,COUNT(*)
FROM TRANSACTIONS
GROUP BY TRANS_ID
HAVING COUNT(*)>1;


-- NULL CHECK
SELECT COUNT(*)
FROM ACCOUNTS
WHERE ACCOUNT_ID IS NULL;

SELECT COUNT(*)
FROM CLIENTS
WHERE CLIENT_ID IS NULL;

SELECT COUNT(*)
FROM LOAN
WHERE LOAN_ID IS NULL;

SELECT COUNT(*)
FROM TRANSACTIONS
WHERE TRANS_ID IS NULL;

-- RENAME DISTRICT TABLE COLUMNS
ALTER TABLE DISTRICT RENAME COLUMN A1 TO DISTRICT_ID;

ALTER TABLE DISTRICT RENAME COLUMN A2 TO DISTRICT_NAME;

ALTER TABLE DISTRICT RENAME COLUMN A3 TO REGION;

ALTER TABLE DISTRICT RENAME COLUMN A4 TO POPULATION;

ALTER TABLE DISTRICT RENAME COLUMN A5 TO MUNICIPALITIES_LT_500;

ALTER TABLE DISTRICT RENAME COLUMN A6 TO MUNICIPALITIES_500_1999;

ALTER TABLE DISTRICT RENAME COLUMN A7 TO MUNICIPALITIES_2000_9999;

ALTER TABLE DISTRICT RENAME COLUMN A8 TO MUNICIPALITIES_GT_10000;

ALTER TABLE DISTRICT RENAME COLUMN A9 TO NUMBER_OF_CITIES;

ALTER TABLE DISTRICT RENAME COLUMN A10 TO URBAN_POPULATION_PERCENT;

ALTER TABLE DISTRICT RENAME COLUMN A11 TO AVG_SALARY;

ALTER TABLE DISTRICT RENAME COLUMN A12 TO UNEMPLOYMENT_RATE_1995;

ALTER TABLE DISTRICT RENAME COLUMN A13 TO UNEMPLOYMENT_RATE_1996;

ALTER TABLE DISTRICT RENAME COLUMN A14 TO ENTREPRENEURS_PER_1000;

ALTER TABLE DISTRICT RENAME COLUMN A15 TO CRIMES_1995;

ALTER TABLE DISTRICT RENAME COLUMN A16 TO CRIMES_1996;
