--1.TOTAL CUSTOMERS
SELECT COUNT(*) AS TOTAL_CUSTOMERS
FROM CLIENTS;

--2.CUSTOMERS BY REGION
SELECT D.REGION, COUNT(C.CLIENT_ID) AS CUSTOMER_COUNT
FROM CLIENTS C
JOIN DISTRICT D
ON C.DISTRICT_ID=D.DISTRICT_ID
GROUP BY D.REGION
ORDER BY CUSTOMER_COUNT DESC;

--3.CUSTOMERS WITH MULTIPLE ACCOUNTS
SELECT CLIENT_ID,COUNT(ACCOUNT_ID) AS ACCOUNT_COUNT
FROM DISPOSITION
WHERE TYPE='OWNER'
GROUP BY CLIENT_ID
HAVING COUNT(ACCOUNT_ID)>1;

--4.CUSTOMER WITHOUT LOANS
SELECT
C.CLIENT_ID
FROM CLIENTS C
JOIN DISPOSITION D
ON C.CLIENT_ID=D.CLIENT_ID
LEFT JOIN LOAN L
ON D.ACCOUNT_ID=L.ACCOUNT_ID
WHERE L.LOAN_ID IS NULL;

-- Insight:
-- Identifies customers who have never taken a loan.
-- Business Recommendation:
-- These customers represent potential targets for loan promotions and cross-selling campaigns.