--5.TRANSACTION OVERVIEW
SELECT COUNT(*) AS  TOTAL_TRANSACTIONS,
SUM(AMOUNT)AS TOTAL_AMOUNT
FROM TRANSACTIONS;

--6.TRANSACTION TYPE ANALYSIS
SELECT
    CASE
        WHEN TYPE = 'PRIJEM' THEN 'Credit'
        WHEN TYPE = 'VYDAJ' THEN 'Debit'
        WHEN TYPE = 'VYBER' THEN 'Cash Withdrawal'
        ELSE TYPE
    END AS TRANSACTION_TYPE,
    COUNT(*) AS TRANSACTION_COUNT,
    SUM(AMOUNT) AS TOTAL_AMOUNT
FROM TRANSACTIONS
GROUP BY TYPE;

--7.OPERATION ANALYSIS
SELECT
    CASE
        WHEN OPERATION = 'VKLAD' THEN 'Cash Deposit'
        WHEN OPERATION = 'VYBER' THEN 'Cash Withdrawal'
        WHEN OPERATION = 'PREVOD Z UCTU' THEN 'Transfer From Account'
        WHEN OPERATION = 'PREVOD NA UCET' THEN 'Transfer To Account'
        WHEN OPERATION = 'VYBER KARTOU' THEN 'Card Withdrawal'
        ELSE NVL(OPERATION, 'Unknown')
    END AS OPERATION,
    COUNT(*) AS TRANSACTION_COUNT,
    SUM(AMOUNT) AS TOTAL_AMOUNT
FROM TRANSACTIONS
GROUP BY OPERATION
ORDER BY TOTAL_AMOUNT DESC;

--8.MONTHLY TREND
SELECT TO_CHAR(TRANS_DATE,'YYYY-MM') MONTH,
COUNT(*) AS TRANSACTIONS,
SUM(AMOUNT) AS AMOUNT
FROM TRANSACTIONS
GROUP BY TO_CHAR(TRANS_DATE,'YYYY-MM')
ORDER BY MONTH;

-- Insight:
-- Tracks transaction activity over time to identify seasonal trends.
-- Business Recommendation:
-- Monthly trends can support resource planning, cash flow management, and forecasting future transaction volumes.

--9.PURPOSE ANALYSIS
SELECT
    CASE
        WHEN K_SYMBOL = 'UVER' THEN 'Loan Payment'
        WHEN K_SYMBOL = 'UROK' THEN 'Interest'
        WHEN K_SYMBOL = 'SIPO' THEN 'Utility Payment'
        WHEN K_SYMBOL = 'POJISTNE' THEN 'Insurance'
        WHEN K_SYMBOL = 'SLUZBY' THEN 'Service Charges'
        WHEN K_SYMBOL = 'DUCHOD' THEN 'Pension'
        WHEN K_SYMBOL = 'SANKC. UROK' THEN 'Penalty Interest'
        ELSE NVL(K_SYMBOL, 'Unknown')
    END AS PURPOSE,
    COUNT(*) AS TRANSACTION_COUNT,
    SUM(AMOUNT) AS TOTAL_AMOUNT
FROM TRANSACTIONS
GROUP BY K_SYMBOL
ORDER BY TOTAL_AMOUNT DESC;

--10.TOP ACCOUNTS
SELECT *
FROM
(
SELECT ACCOUNT_ID, SUM(AMOUNT) TOTAL_AMOUNT,
RANK() OVER (ORDER BY SUM(AMOUNT) DESC) RNK
FROM TRANSACTIONS
GROUP BY ACCOUNT_ID
)
WHERE RNK<=10;