--14.CUSTOMER RANKING
SELECT CLIENT_ID,TOTAL_AMOUNT,
DENSE_RANK() OVER (ORDER BY TOTAL_AMOUNT DESC) RANKING
FROM
(
SELECT D.CLIENT_ID,SUM(T.AMOUNT)AS TOTAL_AMOUNT
FROM TRANSACTIONS T
JOIN DISPOSITION D
ON T.ACCOUNT_ID=D.ACCOUNT_ID
GROUP BY D.CLIENT_ID
);

--15.PREVIOUS TRANSACTION
SELECT ACCOUNT_ID, TRANS_DATE, AMOUNT,
LAG(AMOUNT) OVER( PARTITION BY ACCOUNT_ID ORDER BY TRANS_DATE)AS PREVIOUS_AMOUNT
FROM TRANSACTIONS;

--16.ABOVE AVERAGE CUSTOMERS
WITH CUSTOMER_TOTAL AS
(
SELECT D.CLIENT_ID, SUM(T.AMOUNT) AS TOTAL_SPEND
FROM TRANSACTIONS T
JOIN DISPOSITION D
ON T.ACCOUNT_ID=D.ACCOUNT_ID
GROUP BY D.CLIENT_ID
)

SELECT * FROM CUSTOMER_TOTAL
WHERE TOTAL_SPEND >( SELECT AVG(TOTAL_SPEND) FROM CUSTOMER_TOTAL);

-- Insight:
-- Identifies customers whose total transaction amount exceeds the overall average.
-- Business Recommendation:
-- These customers can be targeted for loyalty programs, premium banking products, and personalized financial services.
