--VIEW
CREATE VIEW ACCOUNT_SUMMARY AS

SELECT ACCOUNT_ID,
COUNT(TRANS_ID) AS TOTAL_TRANSACTIONS,
SUM(AMOUNT)AS TOTAL_AMOUNT,
AVG(BALANCE)AS AVG_BALANCE
FROM TRANSACTIONS
GROUP BY ACCOUNT_ID;

--INDEX
CREATE INDEX IDX_TRANSACTION_ACCOUNT
ON TRANSACTIONS(ACCOUNT_ID);
CREATE INDEX IDX_TRANSACTION_DATE
ON TRANSACTIONS(TRANS_DATE);