--HIGHEST TRANSACTION ACCOUNTS
SELECT *
FROM ACCOUNT_SUMMARY
ORDER BY TOTAL_AMOUNT DESC;

-- HIGH RISK LOANS
SELECT
STATUS,
COUNT(*)AS LOAN_COUNT,
SUM(AMOUNT) AS EXPOSURE
FROM LOAN
WHERE STATUS IN ('B','D')
GROUP BY STATUS;

--MOST USED BANKING OPERATIONS
SELECT
OPERATION,
COUNT(*) AS USAGE
FROM TRANSACTIONS
GROUP BY OPERATION
ORDER BY USAGE DESC;